<template>
  <div class="deal clear">
    <router-view></router-view>
    <deal-slider></deal-slider>
  </div>
</template>
<script>
  import Vue from "vue"
  import DealSlider from "./dealSlider.vue"
  import {mapState} from "vuex"
  export default {
    name:"deal",
    components:{
      DealSlider
    },
    computed:mapState({
      state:state=>state.myDeal,
      /*获取数据*/
    }),
    created(){

      /*var arr = [
        {
          mainInfo:{//协议头部一些信息
            name:"我发送的协议甲1",
            time:"2017.09.28",
            dealState:"签订中",
            myRole:"甲方",
          },
          content:{
            firstParty:{
              name:"CCDI",
              comment:{
                start:"",
                text:"",
              },
            },
            secondParty:{
              name:'com.ICBC',
              comment:{
                start:"3",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
              },
              member:[
                {
                  name:"Linux",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"Microsoft",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"MacOS",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
              ]
            },
            partyContent:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            stageTask:[
              {
                taskState:"确定执行方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付前'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付中'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'已支付'
              },
            ],
            cost:"￥12000",
            modeOfPayment:"线下交易",
            remarksInfo:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            accessory:{
              showText:"与奚地国际签订的协议附件.doc",
              fileAddress:"#/yhzx/deal/sendDealIndex/sendDeal"
            }
          },
          relatedNeeds:[
            {dealName:"需求1",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
            {dealName:"需求2",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
          ],
          agreement:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
        },
        {
          mainInfo:{//协议头部一些信息
            name:"我发送的协议甲2",
            time:"2017.09.28",
            dealState:"履行中",
            myRole:"甲方",
          },
          content:{
            firstParty:{
              name:"CCDI",
              comment:{
                start:"",
                text:"",
              },
            },
            secondParty:{
              name:'com.ICBC',
              comment:{
                start:"3",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
              },
              member:[
                {
                  name:"Linux",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"Microsoft",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"MacOS",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
              ]
            },
            partyContent:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            stageTask:[
              {
                taskState:"确定执行方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付前'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付中'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'已支付'
              },
            ],
            cost:"￥12000",
            modeOfPayment:"线下交易",
            remarksInfo:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            accessory:{
              showText:"与奚地国际签订的协议附件.doc",
              fileAddress:"#/yhzx/deal/sendDealIndex/sendDeal"
            }
          },
          relatedNeeds:[
            {dealName:"需求1",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
            {dealName:"需求2",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
          ],
          agreement:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
        },
        {
          mainInfo:{//协议头部一些信息
            name:"我发送的协议甲3",
            time:"2017.09.28",
            dealState:"协议完成",
            myRole:"甲方",
          },
          content:{
            firstParty:{
              name:"CCDI",
              comment:{
                start:"",
                text:"",
              },
            },
            secondParty:{
              name:'com.ICBC',
              comment:{
                start:"3",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
              },
              member:[
                {
                  name:"Linux",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"Microsoft",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"MacOS",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
              ]
            },
            partyContent:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            stageTask:[
              {
                taskState:"确定执行方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付前'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付中'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'已支付'
              },
            ],
            cost:"￥12000",
            modeOfPayment:"线下交易",
            remarksInfo:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            accessory:{
              showText:"与奚地国际签订的协议附件.doc",
              fileAddress:"#/yhzx/deal/sendDealIndex/sendDeal"
            }
          },
          relatedNeeds:[
            {dealName:"需求1",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
            {dealName:"需求2",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
          ],
          agreement:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",

        },
        {
          mainInfo:{//协议头部一些信息
            name:"我发送的协议甲4",
            time:"2017.09.28",
            dealState:"评价完成",
            myRole:"甲方",
          },
          content:{
            firstParty:{
              name:"CCDI",
              comment:{
                start:"3",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
              },
            },
            secondParty:{
              name:'com.ICBC',
              comment:{
                start:"4",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.乙方团队评价",
              },
              member:[
                {
                  name:"Linux",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"1",
                    text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.乙方个人评价1",
                  },
                },
                {
                  name:"Microsoft",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"2",
                    text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.乙方个人评价2",
                  },
                },
                {
                  name:"MacOS",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"3",
                    text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.乙方个人评价3",
                  },
                },
              ]
            },
            partyContent:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            stageTask:[
              {
                taskState:"确定执行方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付前'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付中'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'已支付'
              },
            ],
            cost:"￥12000",
            modeOfPayment:"线下交易",
            remarksInfo:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            accessory:{
              showText:"与奚地国际签订的协议附件.doc",
              fileAddress:"#/yhzx/deal/sendDealIndex/sendDeal"
            }
          },
          relatedNeeds:[
            {dealName:"需求1",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
            {dealName:"需求2",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
          ],
          agreement:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
        },
        {
          mainInfo:{//协议头部一些信息
            name:"我发送的协议甲5",
            time:"2017.09.28",
            dealState:"审核中",
            myRole:"甲方",
          },
          content:{
            firstParty:{
              name:"CCDI",
              comment:{
                start:"",
                text:"",
              },
            },
            secondParty:{
              name:'com.ICBC',
              comment:{
                start:"3",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
              },
              member:[
                {
                  name:"Linux",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"Microsoft",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"MacOS",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
              ]
            },
            partyContent:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            stageTask:[
              {
                taskState:"确定执行方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付前'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付中'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'已支付'
              },
            ],
            cost:"￥12000",
            modeOfPayment:"线下交易",
            remarksInfo:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            accessory:{
              showText:"与奚地国际签订的协议附件.doc",
              fileAddress:"#/yhzx/deal/sendDealIndex/sendDeal"
            }
          },
          relatedNeeds:[
            {dealName:"需求1",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
            {dealName:"需求2",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
          ],
          agreement: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",

        },
        {
          mainInfo:{//协议头部一些信息
            name:"我发送的协议乙1",
            time:"2017.09.28",
            dealState:"签订中",
            myRole:"乙方",
          },
          content:{
            firstParty:{
              name:"CCDI",
              comment:{
                start:"",
                text:"",
              },
            },
            secondParty:{
              name:'com.ICBC',
              comment:{
                start:"3",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
              },
              member:[
                {
                  name:"Linux",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"Microsoft",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"MacOS",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
              ]
            },
            partyContent:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            stageTask:[
              {
                taskState:"确定执行方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付前'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付中'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'已支付'
              },
            ],
            cost:"￥12000",
            modeOfPayment:"线下交易",
            remarksInfo:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            accessory:{
              showText:"与奚地国际签订的协议附件.doc",
              fileAddress:"#/yhzx/deal/sendDealIndex/sendDeal"
            }
          },
          relatedNeeds:[
            {dealName:"需求1",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
            {dealName:"需求2",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
          ],
          agreement:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
        },
        {
          mainInfo:{//协议头部一些信息
            name:"我发送的协议乙2",
            time:"2017.09.28",
            dealState:"履行中",
            myRole:"乙方",
          },
          content:{
            firstParty:{
              name:"CCDI",
              comment:{
                start:"",
                text:"",
              },
            },
            secondParty:{
              name:'com.ICBC',
              comment:{
                start:"3",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
              },
              member:[
                {
                  name:"Linux",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:"职责1；职责2；职责3",
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"Microsoft",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:"职责1；职责2；职责3",
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"MacOS",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:"职责1；职责2；职责3",
                  comment:{
                    start:"",
                    text:"",
                  },
                },
              ]
            },
            partyContent:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            stageTask:[
              {
                taskState:"确定执行方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付前'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付中'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'已支付'
              },
            ],
            cost:"￥12000",
            modeOfPayment:"线下交易",
            remarksInfo:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            accessory:{
              showText:"与奚地国际签订的协议附件.doc",
              fileAddress:"#/yhzx/deal/sendDealIndex/sendDeal"
            }
          },
          relatedNeeds:[
            {dealName:"需求1",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
            {dealName:"需求2",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
          ],
          agreement:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
        },
        {
          mainInfo:{//协议头部一些信息
            name:"我发送的协议乙3",
            time:"2017.09.28",
            dealState:"协议完成",
            myRole:"乙方",
          },
          content:{
            firstParty:{
              name:"CCDI",
              comment:{
                start:"",
                text:"",
              },
            },
            secondParty:{
              name:'com.ICBC',
              comment:{
                start:"3",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
              },
              member:[
                {
                  name:"Linux",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"Microsoft",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"MacOS",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
              ]
            },
            partyContent:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            stageTask:[
              {
                taskState:"确定执行方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付前'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付中'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'已支付'
              },
            ],
            cost:"￥12000",
            modeOfPayment:"线下交易",
            remarksInfo:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            accessory:{
              showText:"与奚地国际签订的协议附件.doc",
              fileAddress:"#/yhzx/deal/sendDealIndex/sendDeal"
            }
          },
          relatedNeeds:[
            {dealName:"需求1",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
            {dealName:"需求2",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
          ],
          agreement:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",

        },
        {
          mainInfo:{//协议头部一些信息
            name:"我发送的协议乙4",
            time:"2017.09.28",
            dealState:"评价完成",
            myRole:"乙方",
          },
          content:{
            firstParty:{
              name:"CCDI",
              comment:{
                start:"3",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
              },
            },
            secondParty:{
              name:'com.ICBC',
              comment:{
                start:"3",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
              },
              comment:{
                start:"3",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
              },
              member:[
                {
                  name:"Linux",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"Microsoft",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"MacOS",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
              ]
            },
            partyContent:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            stageTask:[
              {
                taskState:"确定执行方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付前'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付中'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'已支付'
              },
            ],
            cost:"￥12000",
            modeOfPayment:"线下交易",
            remarksInfo:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            accessory:{
              showText:"与奚地国际签订的协议附件.doc",
              fileAddress:"#/yhzx/deal/sendDealIndex/sendDeal"
            }
          },
          relatedNeeds:[
            {dealName:"需求1",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
            {dealName:"需求2",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
          ],
          agreement:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
        },
        {
          mainInfo:{//协议头部一些信息
            name:"我发送的协议乙5",
            time:"2017.09.28",
            dealState:"审核中",
            myRole:"乙方",
          },
          content:{
            firstParty:{
              name:"CCDI",
              comment:{
                start:"",
                text:"",
              },
            },
            secondParty:{
              name:'com.ICBC',
              comment:{
                start:"3",
                text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
              },
              member:[
                {
                  name:"Linux",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"Microsoft",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
                {
                  name:"MacOS",
                  avatar:require("../../assets/img/deal/sendDeal/avatar.png"),
                  responsibilities:["职责1；","职责2；","职责3"],
                  comment:{
                    start:"",
                    text:"",
                  },
                },
              ]
            },
            partyContent:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            stageTask:[
              {
                taskState:"确定执行方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付前'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'支付中'
              },
              {
                taskState:"开始执行已定方案",
                time:"2017.05.06—2017.09.28",
                taskDetail:"出具详细方案以及相关数据",
                price:"￥6000",
                section:'已支付'
              },
            ],
            cost:"￥12000",
            modeOfPayment:"线下交易",
            remarksInfo:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
            accessory:{
              showText:"与奚地国际签订的协议附件.doc",
              fileAddress:"#/yhzx/deal/sendDealIndex/sendDeal"
            }
          },
          relatedNeeds:[
            {dealName:"需求1",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
            {dealName:"需求2",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
          ],
          agreement: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",

        },
      ];

      Vue.set(this.state,"dealInfo",arr)*/
    }
  }
</script>
<style scoped lang="scss">

  .deal{
    width: 1200px;
    min-height: 346px;
  }
</style>
