function ajaxData() {
  var outlineDeal=[
    {
      mainInfo:{//协议头部一些信息
        name:"协议草稿1",
        time:"2017.09.28",
        dealState:"被管理员退回",
        myRole:"乙方",
      },
      content:{
        firstParty:{
          name:"CCDI",
          comment:{
            start:"3",
            text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
          },
        },
        secondParty:{
          name:'com.ICBC',
          comment:{
            start:"3",
            text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
          },
          comment:{
            start:"3",
            text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
          },
          member:[
            {
              name:"Linux",
              avatar:require("../../../assets/img/deal/sendDeal/avatar.png"),
              responsibilities:["职责1；","职责2；","职责3"],
              comment:{
                start:"",
                text:"",
              },
            },
            {
              name:"Microsoft",
              avatar:require("../../../assets/img/deal/sendDeal/avatar.png"),
              responsibilities:["职责1；","职责2；","职责3"],
              comment:{
                start:"",
                text:"",
              },
            },
            {
              name:"MacOS",
              avatar:require("../../../assets/img/deal/sendDeal/avatar.png"),
              responsibilities:["职责1；","职责2；","职责3"],
              comment:{
                start:"",
                text:"",
              },
            },
          ]
        },
        partyContent:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
        stageTask:[
          {
            taskState:"确定执行方案",
            time:"2017.05.06—2017.09.28",
            taskDetail:"出具详细方案以及相关数据",
            price:"￥6000",
            section:'支付前'
          },
          {
            taskState:"开始执行已定方案",
            time:"2017.05.06—2017.09.28",
            taskDetail:"出具详细方案以及相关数据",
            price:"￥6000",
            section:'支付中'
          },
          {
            taskState:"开始执行已定方案",
            time:"2017.05.06—2017.09.28",
            taskDetail:"出具详细方案以及相关数据",
            price:"￥6000",
            section:'已支付'
          },
        ],
        cost:"￥12000",
        modeOfPayment:"线下交易",
        remarksInfo:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
        accessory:{
          showText:"与奚地国际签订的协议附件.doc",
          fileAddress:"#/yhzx/deal/sendDealIndex/sendDeal"
        }
      },
      relatedNeeds:[
        {dealName:"需求1",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
        {dealName:"需求2",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
      ],
      agreement:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
    },
    {
      mainInfo:{//协议头部一些信息
        name:"协议草稿2",
        time:"2017.09.28",
        dealState:"",
        myRole:"乙方",
      },
      content:{
        firstParty:{
          name:"CCDI",
          comment:{
            start:"",
            text:"",
          },
        },
        secondParty:{
          name:'com.ICBC',
          comment:{
            start:"3",
            text:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
          },
          member:[
            {
              name:"Linux",
              avatar:require("../../../assets/img/deal/sendDeal/avatar.png"),
              responsibilities:["职责1；","职责2；","职责3"],
              comment:{
                start:"",
                text:"",
              },
            },
            {
              name:"Microsoft",
              avatar:require("../../../assets/img/deal/sendDeal/avatar.png"),
              responsibilities:["职责1；","职责2；","职责3"],
              comment:{
                start:"",
                text:"",
              },
            },
            {
              name:"MacOS",
              avatar:require("../../../assets/img/deal/sendDeal/avatar.png"),
              responsibilities:["职责1；","职责2；","职责3"],
              comment:{
                start:"",
                text:"",
              },
            },
          ]
        },
        partyContent:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
        stageTask:[
          {
            taskState:"确定执行方案",
            time:"2017.05.06—2017.09.28",
            taskDetail:"出具详细方案以及相关数据",
            price:"￥6000",
            section:'支付前'
          },
          {
            taskState:"开始执行已定方案",
            time:"2017.05.06—2017.09.28",
            taskDetail:"出具详细方案以及相关数据",
            price:"￥6000",
            section:'支付中'
          },
          {
            taskState:"开始执行已定方案",
            time:"2017.05.06—2017.09.28",
            taskDetail:"出具详细方案以及相关数据",
            price:"￥6000",
            section:'已支付'
          },
        ],
        cost:"￥12000",
        modeOfPayment:"线下交易",
        remarksInfo:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",
        accessory:{
          showText:"与奚地国际签订的协议附件.doc",
          fileAddress:"#/yhzx/deal/sendDealIndex/sendDeal"
        }
      },
      relatedNeeds:[
        {dealName:"需求1",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
        {dealName:"需求2",viewThePath:"#/yhzx/deal/sendDealIndex/sendDeal"},
      ],
      agreement: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur, ea, veritatis? A ad adipisci assumenda doloribus et eveniet laborum ratione sapiente. Ad corporis doloremque, nam officia officiis rem tempore ut.",

    },
  ];

  return outlineDeal;

}
export {ajaxData}
