export default{
	state:{
		companyMessage:{
			accountInfo:{
				registerTime:"2017.08.08",
				companyMail:"666666.@ccdi.com",
				passwords:"999999",
				contacts:[
					{
						name:"玛卡",
						phoneNum:"156123456789"
					},
					{
						name:"瑞纳",
						phoneNum:"156123456789"
					}
			      
			    ],
			},
			basicInfo:{
				logo:"",
			    companyName:"CCDI悉地国际",
			    companyAddress:"四平路1758号",
			    companyDesc:"CCDI悉地国际（以下简称“CCDI”）创立于1994年，是在城市建设和开发领域从事综合专业服务的大型工程实践咨询机构。我们拥有上海、北京、深圳、成都、纽约五大区域，在重庆、南京、天津、武汉、西安、昆明等国内主要城市设置分公司或办事处，实现在遍布全国各地的服务网络。CCDI曾成功主持设计了国家游泳中心“水立方”、国家网球中心、深圳平安国际金融大厦、上海洛克菲勒外滩源、济南奥林匹克体育中心、深圳大梅沙·万科中心、杭州奥体博览中心、哈尔滨西客站、哈尔滨太平国际机场、北京昆仑公寓、深圳华润中心二期、天津万科水晶城、天津港国际邮轮码头客运大厦等各类型知名项目，共完成项目3000多项，完成的设计及工程技术服务项目总面积超过2亿平方米，实现了大量自主创新和绿色环保的科技成果。",
			    companyPhone:"77777777",
			    
			},
			companyCerInfo:{
				companyLicense:"",
				companyApitute:""
			},
			companyOrgaInfo:{
			
				senior:[
					{
						id:"",
						dealId:"高管叫啥"
					},{
						id:"",
						dealId:"高管叫啥aa",
					},{
						id:"",
						dealId:"高管叫啥22",
					},{
						id:"",
						dealId:"高管叫啥",
					},{
						id:"",
						dealId:"高管叫啥",
					},{
						id:"",
						dealId:"高管叫啥",
					},
					
				],
				backbone:[
					{
						id:"",
						dealId:"骨干叫啥"
					},{
						id:"",
						dealId:"骨干叫啥"
					},{
						id:"",
						dealId:"骨干叫啥"
					},{
						id:"",
						dealId:"骨干叫啥"
					},{
						id:"",
						dealId:"骨干叫啥"
					},{
						id:"",
						dealId:"骨干叫啥"
					}
				
				],
				staff:{
					"certified":[
						{
							id:"",
							dealId:"我已认证"
						},
						{
							id:"",
							dealId:"我已认证"
						},
						{
							id:"",
							dealId:"我已认证"
						},{
							id:"",
							dealId:"我已认证"
						},
						{
							id:"",
							dealId:"我已认证"
						},
						{
							id:"",
							dealId:"我已认证"
						},{
							id:"",
							dealId:"我已认证"
						},
						{
							id:"",
							dealId:"我已认证"
						},
						{
							id:"",
							dealId:"我已认证"
						},{
							id:"",
							dealId:"我已认证"
						},
						{
							id:"",
							dealId:"我已认证"
						},
						{
							id:"",
							dealId:"我已认证"
						},
					],
					"uncertified":[
						{
							id:"",
							dealId:"我未认证aa"
						},
						{
							id:"",
							dealId:"我未认证"
						},
						{
							id:"",
							dealId:"我未认证"
						},{
							id:"",
							dealId:"我未认证"
						},
						{
							id:"",
							dealId:"我未认证"
						},
						{
							id:"",
							dealId:"我未认证"
						},{
							id:"",
							dealId:"我未认证"
						},
						{
							id:"",
							dealId:"我未认证"
						},
						{
							id:"",
							dealId:"我未认证"
						},{
							id:"",
							dealId:"我未认证"
						},
						{
							id:"",
							dealId:"我未认证"
						},
						{
							id:"",
							dealId:"我未认证kk"
						},
					]
				},
				
			},
			companyProInfo:[
				{
					id:"1",
					proName:" Water Cube",
					proPlace:"北京市朝阳区",
					proState:"建成",
					compalteTime_S:"2005-8-1",//建成开始时间
					compalteTime_E:"2008-8-1",//建成结束时间
					proFunc:"体育场馆",
					proDesc:"国家游泳中心是北京2008年奥运会主要比赛场馆之一，也是2008年北京奥运会标志性建筑物之一。[2]  具有国际级的设施水平和知名度，周边拥有超过50万人的消费居民群体，",
					proPics:"",//项目图片——————以上是项目基本信息
					parTakeTime_S:"2004-7-1",//我参与的开始时间
					parTakeTime_E:"2008-7-1",//我参与的结束时间
					takeOffice:"建筑设计",//职责
					detailDes:"等会我佛教法兰斯热人体褪法国红酒看了下橙我的过去我热热天气挖到了收付款啦国家游泳中心是北京2008年奥运会主要比赛场馆之一，也是2008年北京奥运会标志性建筑物之一。[2]  具有国际级的设施水平和知名度，周边拥有超过50万人的消费居民群体，",
					picsDisplay:"",//我上传的图片展示
					companies:[//参与公司
						{
							id:"1111",
							name:"聚星科技",
							takeOffice:"材料",
							parTakeTime_S:"2004-7-1",
							parTakeTime_E:"2008-7-1",
							certify:true,//是否认证
						},{
							id:"1111",
							name:"悉地国际",
							takeOffice:"建筑设计",
							parTakeTime_S:"2004-7-1",
							parTakeTime_E:"2015-7-1",
							certify:false,
						},
					],
					teams:[//参与团队
						{
							id:"1111",
							name:"建筑梦之队",
							takeOffice:"材料",
							parTakeTime_S:"2004-7-1",
							parTakeTime_E:"2008-7-1",
							certify:true,
						},{
							id:"1111",
							name:"悉地国际团队",
							takeOffice:"建筑设计",
							parTakeTime_S:"2004-7-1",
							parTakeTime_E:"2015-7-1",
							certify:false,
						},
					],
					person:[//参与个人
						{
							id:"1111",
							name:"黄浦铁牛",
							takeOffice:"材料",
							parTakeTime_S:"2004-7-1",
							parTakeTime_E:"2008-7-1",
							certify:true,
						},{
							id:"1111",
							name:"南宫翠花",
							takeOffice:"建筑设计",
							parTakeTime_S:"2004-7-1",
							parTakeTime_E:"2015-7-1",
							certify:false,
						},
					]

				},
				{
					id:"2",
					proName:"水立方 Water Cube",
					proPlace:"北京市朝阳区",
					proState:"建成",
					compalteTime_S:"2005-8-1",
					compalteTime_E:"2008-8-1",
					proFunc:"体育场馆",
					proDesc:"国家游泳中心是北京2008年奥运会主要比赛场馆之一，也是2008年北京奥运会标志性建筑物之一。[2]  具有国际级的设施水平和知名度，周边拥有超过50万人的消费居民群体，",
					proPics:"",
					parTakeTime_S:"2004-7-1",
					parTakeTime_E:"2008-7-1",
					takeOffice:"工程造价",
					detailDes:"等会我佛教法兰斯热人体褪法国红酒看了下橙我的过去我热热天气挖到了收付款啦国家游泳中心是北京2008年奥运会主要比赛场馆之一，也是2008年北京奥运会标志性建筑物之一。[2]  具有国际级的设施水平和知名度，周边拥有超过50万人的消费居民群体，",
					picsDisplay:"",
					companies:[
						{
							id:"1111",
							name:"聚星科技",
							takeOffice:"材料",
							parTakeTime_S:"2004-7-1",
							parTakeTime_E:"2008-7-1",
							certify:true,
						},{
							id:"1111",
							name:"悉地国际",
							takeOffice:"建筑设计",
							parTakeTime_S:"2004-7-1",
							parTakeTime_E:"2015-7-1",
							certify:false,
						},
					],
					teams:[
						{
							id:"1111",
							name:"建筑梦之队",
							takeOffice:"材料",
							parTakeTime_S:"2004-7-1",
							parTakeTime_E:"2008-7-1",
							certify:true,
						},{
							id:"1111",
							name:"悉地国际团队",
							takeOffice:"建筑设计",
							parTakeTime_S:"2004-7-1",
							parTakeTime_E:"2015-7-1",
							certify:false,
						},
					],
					person:[
						{
							id:"1111",
							name:"黄浦铁牛",
							takeOffice:"材料",
							parTakeTime_S:"2004-7-1",
							parTakeTime_E:"2008-7-1",
							certify:true,
						},{
							id:"1111",
							name:"南宫翠花",
							takeOffice:"建筑设计",
							parTakeTime_S:"2004-7-1",
							parTakeTime_E:"2015-7-1",
							certify:false,
						},
					]

				}
			],
			companyTeamInfo:[
					{
						id:"",
						dealId:"水立方团队",
						cerState:true,
					},
					{
						id:"",
						dealId:"鸟巢团队",
						cerState:true,
					},
					{
						id:"",
						dealId:"长城团队",
						cerState:false,
					},
					{
						id:"",
						dealId:"世博馆团队",
						cerState:false,
					}
				
			]
			
			
			    
			    

				
			
		}
	},
	mutations:{
		ediContactors:(state,info)=>{state.companyMessage.accountInfo.contacts=info}
	}
}
