export default{
	state:{
		detailInfo:{
			id:"000",
			pubID:"888",
			name:'滴水湖"你来啦客栈"',//需求名称
			describe:"客栈坐落于丽江南门八河季宝屋东段12号，客栈周边都居住着淳朴的纳西居民，客栈门前就是小河，小桥流水缓缓流淌，客栈的房间配备了舒适齐全的各项设施，客栈占地约300平方米，有大床房，标间，房间阳光充足，阳光灿烂的院子四季花开满庭芬芳，宽敞明亮的自助厨房分了品酒区品茶区和烤火区，无论一啜清茶，还是一盏红酒，都能给您一个悠雅的假期。一语一解悟，一花一世界，一舍一心境，这就是落座于大研古城南门八河的“naxi88客栈”，是时候给自己一个心灵静谧的空间；客栈到大研古城南门口只需3分钟，到大研古镇和白沙古镇分别为20分钟车程，20元左右车费，机场到客栈45分钟，火车站到客栈20分钟，交通非常便利。如果是客栈安排接机，司机可以直接送您到客栈门口，免除您搬运行李之辛劳。在丽江，在naxi88客栈，我们在这里等你。",//需求描述
			complateTime:"2016.7.5",//完成时间
			demandObj:["个人","团队",""],//对象
			objRequire:"一级建造师",//对象的要求
			reword:"20万人民币",//酬劳
			remark:"大家利用各种稀奇古怪啼笑皆非的方式治疗缓解客人，是客栈最与众不同的特色，也成了这个城市一道亮丽的风景线。虽然也有误会和危机，但是大家一起面对一起解决，经历种种难题考验后，深藏秘密的老板娘也迎来了新生，丽江客栈，也在欢笑中继续起航",//备注
			applicant:[
				{
					id:"",
					name:"华东设计",
					coIntention:'1', //达成合作意向
				},{
					id:"",
					name:"万达有限公司",
					coIntention:'1', //达成合作意向
				},{
					id:"",
					name:"腾讯",
					coIntention:'0',//未达成合作意向  申请阶段
				},{
					id:"666",
					name:"CCDI",
					coIntention:'1',//达成合作意向  申请阶段
				},
				
			],//申请方
			relatedDeal:[
				{
					name:"华东设计",
					valid:true,
				},{
					name:"万达有限公司",
					valid:false,
				}
			],//关联协议
			auditStatus:"1",//需求审核成功
			havePublished:true,//有没有发布
			haveOffLine:true,//有没有在线
		},
		demandInfo:[//我发布的有效需求
			{
				id:"000",
				pubID:"666",
				name:'滴水湖"你来啦客栈"',//需求名称
				describe:"客栈坐落于丽江南门八河季宝屋东段12号，客栈周边都居住着淳朴的纳西居民，客栈门前就是小河，小桥流水缓缓流淌，客栈的房间配备了舒适齐全的各项设施，客栈占地约300平方米，有大床房，标间，房间阳光充足，阳光灿烂的院子四季花开满庭芬芳，宽敞明亮的自助厨房分了品酒区品茶区和烤火区，无论一啜清茶，还是一盏红酒，都能给您一个悠雅的假期。一语一解悟，一花一世界，一舍一心境，这就是落座于大研古城南门八河的“naxi88客栈”，是时候给自己一个心灵静谧的空间；客栈到大研古城南门口只需3分钟，到大研古镇和白沙古镇分别为20分钟车程，20元左右车费，机场到客栈45分钟，火车站到客栈20分钟，交通非常便利。如果是客栈安排接机，司机可以直接送您到客栈门口，免除您搬运行李之辛劳。在丽江，在naxi88客栈，我们在这里等你。",//需求描述
				complateTime:"2016.7.5",//完成时间
				demandObj:["个人","团队",""],//对象
				objRequire:"一级建造师",//对象的要求
				reword:"20万人民币",//酬劳
				remark:"大家利用各种稀奇古怪啼笑皆非的方式治疗缓解客人，是客栈最与众不同的特色，也成了这个城市一道亮丽的风景线。虽然也有误会和危机，但是大家一起面对一起解决，经历种种难题考验后，深藏秘密的老板娘也迎来了新生，丽江客栈，也在欢笑中继续起航",//备注
				applicant:[
					{
						id:"",
						name:"华东设计",
						coIntention:true,
					},{
						id:"",
						name:"万达有限公司",
						coIntention:true,
					},{
						id:"",
						name:"腾讯",
						coIntention:false,
					},{
						id:"888",
						name:"CCDI",
						coIntention:false,
					},
					
				],//申请方
				relatedDeal:[
					{
						name:"华东设计",
						valid:true,
					},{
						name:"万达有限公司",
						valid:false,
					}
				],//关联协议
				auditStatus:"1",//需求审核成功
				havePublished:true,//有没有发布
				haveOffLine:true,//有没有在线
			},{
				id:"001",
				name:"我有一个需求，你敢接吗？",//需求名称
				describe:"",//需求描述
				complateTime:"2019-11",//完成时间
				demandObj:["","",""],//对象
				objRequire:"",//对象的要求
				reword:"",//酬劳
				remark:"",//备注
				applicant:[
					
				],//申请方
				relatedDeal:[
					{
						name:"华东设计",
						valid:true,
					},{
						name:"万达有限公司",
						valid:false,
					}
				],//关联协议
				auditStatus:"0",//需求正在审核
				havePublished:false,//有没有发布
				haveOffLine:false,//有没有在线
			},{
				id:"002",
				name:"我有一个需求，审核中",//需求名称
				describe:"",//需求描述
				complateTime:"2019-11",//完成时间
				demandObj:["","",""],//对象
				objRequire:"",//对象的要求
				reword:"",//酬劳
				remark:"",//备注
				applicant:[
					
				],//申请方
				relatedDeal:[
					{
						name:"华东设计",
						valid:true,
					},{
						name:"万达有限公司",
						valid:false,
					}
				],//关联协议
				auditStatus:"0",//需求正在审核
				havePublished:false,//有没有发布
				haveOffLine:false,//有没有在线
			}
		],
		unvalidInfo:[//我发布的无效需求
			
		],
		draftInfo:[//我存入草稿箱的需求
			{
				id:"003",
				name:'滴水湖"你来啦客栈"draf',//需求名称
				describe:"客栈坐落于滴水湖南门八河季宝屋东段12号，客栈周边都居住着淳朴的纳西居民，客栈门前就是小河，小桥流水缓缓流淌，客栈的房间配备了舒适齐全的各项设施，客栈占地约300平方米，有大床房，标间，房间阳光充足，阳光灿烂的院子四季花开满庭芬芳，宽敞明亮的自助厨房分了品酒区品茶区和烤火区，无论一啜清茶，还是一盏红酒，都能给您一个悠雅的假期。一语一解悟，一花一世界，一舍一心境，这就是落座于大研古城南门八河的“naxi88客栈”，是时候给自己一个心灵静谧的空间；客栈到大研古城南门口只需3分钟，到大研古镇和白沙古镇分别为20分钟车程，20元左右车费，机场到客栈45分钟，火车站到客栈20分钟，交通非常便利。如果是客栈安排接机，司机可以直接送您到客栈门口，免除您搬运行李之辛劳。在丽江，在naxi88客栈，我们在这里等你。",//需求描述
				complateTime:"2018-10",//完成时间
				demandObj:["个人","",""],//对象
				objRequire:"一级建造师",//对象的要求
				reword:"20万人民币",//酬劳
				remark:"大家利用各种稀奇古怪啼笑皆非的方式治疗缓解客人，是客栈最与众不同的特色，也成了这个城市一道亮丽的风景线。虽然也有误会和危机，但是大家一起面对一起解决，经历种种难题考验后，深藏秘密的老板娘也迎来了新生，丽江客栈，也在欢笑中继续起航",//备注
				applicant:[
					{
						id:"",
						name:"华东设计",
						coIntention:true,
					},{
						id:"",
						name:"万达有限公司",
						coIntention:true,
					},{
						id:"",
						name:"腾讯",
						coIntention:false,
					},
				],//申请方
				relatedDeal:[
					{
						name:"华东设计",
						valid:true,
					},{
						name:"万达有限公司",
						valid:false,
					}
				],//关联协议
				auditStatus:"",//需求正在审核
				havePublished:false,//有没有发布
				haveOffLine:false,//有没有在线
			},
		],
		applicationInfo:[
			{
				id:"100",
				name:'中铁四局安哥拉项目',//需求名称
				describe:"客栈坐落于丽江南门八河季宝屋东段12号，客栈周边都居住着淳朴的纳西居民，客栈门前就是小河，小桥流水缓缓流淌，客栈的房间配备了舒适齐全的各项设施，客栈占地约300平方米，有大床房，标间，房间阳光充足，阳光灿烂的院子四季花开满庭芬芳，宽敞明亮的自助厨房分了品酒区品茶区和烤火区，无论一啜清茶，还是一盏红酒，都能给您一个悠雅的假期。一语一解悟，一花一世界，一舍一心境，这就是落座于大研古城南门八河的“naxi88客栈”，是时候给自己一个心灵静谧的空间；客栈到大研古城南门口只需3分钟，到大研古镇和白沙古镇分别为20分钟车程，20元左右车费，机场到客栈45分钟，火车站到客栈20分钟，交通非常便利。如果是客栈安排接机，司机可以直接送您到客栈门口，免除您搬运行李之辛劳。在丽江，在naxi88客栈，我们在这里等你。",//需求描述
				complateTime:"2018-10",//完成时间
				demandObj:["个人","","团队"],//对象
				objRequire:"一级建造师",//对象的要求
				reword:"",//酬劳
				remark:"大家利用各种稀奇古怪啼笑皆非的方式治疗缓解客人，是客栈最与众不同的特色，也成了这个城市一道亮丽的风景线。虽然也有误会和危机，但是大家一起面对一起解决，经历种种难题考验后，深藏秘密的老板娘也迎来了新生，丽江客栈，也在欢笑中继续起航",//备注
				applicant:[
					{
						id:"",
						name:"华东设计",
						coIntention:true,
					},{
						id:"",
						name:"北京万达万达万达股份有限公司",
						coIntention:true,
					},{
						id:"",
						name:"腾讯",
						coIntention:false,
					},{
						id:"666",
						name:"CCDI",
						coIntention:true,
					},{
						id:"667",
						name:"哒哒",
						coIntention:false,
					},{
						id:"668",
						name:"滴滴",
						coIntention:false,
					},
				],//申请方
				relatedDeal:[
					{
						name:"华东设计",
						valid:true,
					},{
						name:"万达有限公司",
						valid:false,
					}
				],//关联协议
				auditStatus:"1",
				coIntention:true,//我已经和对方达成合作
			},{
				id:"113",
				name:"嗯，你已经申请了吗？",//需求名称
				describe:"",//需求描述
				complateTime:"2019-11",//完成时间
				demandObj:["","",""],//对象
				objRequire:"",//对象的要求
				reword:"",//酬劳
				remark:"",//备注
				applicant:[
					
				],//申请方
				relatedDeal:[
					{
						name:"华东设计",
						valid:true,
					},{
						name:"万达有限公司",
						valid:false,
					}
				],//关联协议
				auditStatus:"0",
				coIntention:false,//我未和对方达成合作
			}
		
		],
		colletionInfo:[
			{
				id:"100",
				name:'中铁四局安哥拉项目',//需求名称
				describe:"客栈坐落于丽江南门八河季宝屋东段12号，客栈周边都居住着淳朴的纳西居民，客栈门前就是小河，小桥流水缓缓流淌，客栈的房间配备了舒适齐全的各项设施，客栈占地约300平方米，有大床房，标间，房间阳光充足，阳光灿烂的院子四季花开满庭芬芳，宽敞明亮的自助厨房分了品酒区品茶区和烤火区，无论一啜清茶，还是一盏红酒，都能给您一个悠雅的假期。一语一解悟，一花一世界，一舍一心境，这就是落座于大研古城南门八河的“naxi88客栈”，是时候给自己一个心灵静谧的空间；客栈到大研古城南门口只需3分钟，到大研古镇和白沙古镇分别为20分钟车程，20元左右车费，机场到客栈45分钟，火车站到客栈20分钟，交通非常便利。如果是客栈安排接机，司机可以直接送您到客栈门口，免除您搬运行李之辛劳。在丽江，在naxi88客栈，我们在这里等你。",//需求描述
				complateTime:"2018-10",//完成时间
				demandObj:["个人","","团队"],//对象
				objRequire:"一级建造师",//对象的要求
				reword:"20万人民币",//酬劳
				remark:"大家利用各种稀奇古怪啼笑皆非的方式治疗缓解客人，是客栈最与众不同的特色，也成了这个城市一道亮丽的风景线。虽然也有误会和危机，但是大家一起面对一起解决，经历种种难题考验后，深藏秘密的老板娘也迎来了新生，丽江客栈，也在欢笑中继续起航",//备注
				applicant:[
					{
						id:"",
						name:"华东设计",
						coIntention:true,
					},{
						id:"",
						name:"北京万达万达万达股份有限公司",
						coIntention:true,
					},{
						id:"",
						name:"腾讯",
						coIntention:false,
					},{
						id:"666",
						name:"CCDI",
						coIntention:true,
					},{
						id:"667",
						name:"哒哒",
						coIntention:false,
					},{
						id:"668",
						name:"滴滴",
						coIntention:false,
					},
				],//申请方
				relatedDeal:[
					{
						name:"华东设计",
						valid:true,
					},{
						name:"万达有限公司",
						valid:false,
					}
				],//关联协议
				auditStatus:"1",
				coIntention:true,
			},{
				id:"113",
				name:"嗯，你已经申请了吗？",//需求名称
				describe:"",//需求描述
				complateTime:"2019-11",//完成时间
				demandObj:["","",""],//对象
				objRequire:"",//对象的要求
				reword:"",//酬劳
				remark:"",//备注
				applicant:[
					
				],//申请方
				relatedDeal:[
					{
						name:"华东设计",
						valid:true,
					},{
						name:"万达有限公司",
						valid:false,
					}
				],//关联协议
				auditStatus:"0",
				coIntention:false,
			}
		]
		
	}
}
